import 'package:freezed_annotation/freezed_annotation.dart';

part 'task.freezed.dart';
part 'task.g.dart';

enum TaskSource { whatsapp, classroom, gmail, manual }

enum TaskPriority { critical, high, medium, low }

@freezed
class Task with _$Task {
  const Task._();

  const factory Task({
    int? id,
    required String title,
    String? description,
    required TaskSource source,
    int? sourceId,
    @Default(TaskPriority.medium) TaskPriority priority,
    DateTime? deadline,
    DateTime? scheduledStart,
    DateTime? scheduledEnd,
    @Default(false) bool isCompleted,
    @Default(false) bool isDeleted,
    double? aiConfidence,
    required DateTime createdAt,
    required DateTime updatedAt,
    DateTime? completedAt,
  }) = _Task;

  factory Task.fromJson(Map<String, dynamic> json) => _$TaskFromJson(json);

  /// Returns the source as a database-compatible uppercase string.
  String get sourceString => source.name.toUpperCase();

  /// Returns the priority as a database-compatible uppercase string.
  String get priorityString => priority.name.toUpperCase();

  /// Whether this task is overdue.
  bool get isOverdue =>
      deadline != null &&
      !isCompleted &&
      !isDeleted &&
      DateTime.now().isAfter(deadline!);

  /// Whether this task was generated by AI (non-manual source).
  bool get isAiGenerated => source != TaskSource.manual;
}
